chat/urls.py
from django.urls import path


from .views import index,room


urlpatterns = [
    path('', index, name='index'),
    path('chat/<str:room_name>/', room, name='room'),
]

realtimeChat/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include(('chat.urls','chat'),namespace='chat')),
    path('user/',include(('user.urls','user'),namespace='user')),
    
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path


from .views import userlogin,logoutUser,settingProfil
urlpatterns = [
    path("login/", userlogin, name="login"),
    path('logout/',logoutUser,name="logout"),
    path('profil/',settingProfil,name='setting'),
]

chat/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import CharField
from django.utils import tree
from user.models import Usercostumer
# Create your models here.



class Group_room(models.Model):
    room_name = models.CharField(max_length=30,unique=True)
    profil_group =models.ImageField(upload_to='image',default='image/default.jpg')
   

class Chat_log(models.Model):
    user = models.ForeignKey(Usercostumer, related_name='author', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    group = models.ForeignKey(Group_room, on_delete=models.CASCADE)

    class Meta:
        ordering=['timestamp']
        
    def __str__(self):
        return self.user.username
        

user/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class Usercostumer(models.Model):
    CHOICES_status = (
        ('ada' , 'ada'),
        ('busy','busy'),
    )
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    username= models.CharField(max_length=30,default=user)
    profil = models.ImageField(upload_to='image', height_field='height_field', width_field='width_field',default='image/default.jpg')
    bio = models.CharField(max_length=150,default='Hey aku memakai apa ini')
    status = models.CharField(max_length=20,choices=CHOICES_status,default='ada')
    width_field = models.PositiveIntegerField(default=0)
    height_field = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.username

@receiver(post_save,sender=settings.AUTH_USER_MODEL)
def create_usercostumer(sender, instance, created, **kwargs):
    if created:
        Usercostumer.objects.create(
            user=instance,
            username=str(instance.username)
        )

user/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Usercostumer
from django import forms


class FormUser(forms.ModelForm):
    class Meta:
        model = Usercostumer
        fields = [ "profil",'username','status','bio' ]


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email']


# class SignupForm(forms.ModelForm):
#     def __init__(self, *args, **kwargs):
#         super(SignupForm, self).__init__(*args, **kwargs)
#         self.fields['nameD'].widget = forms.TextInput(
#             attrs={'placeholder': 'Enter first name'})
#         self.fields['nameB'].widget = forms.TextInput(
#             attrs={'placeholder': 'Enter last name'})

#     nameD = forms.CharField(max_length=100)
#     nameB = forms.CharField(max_length=100)
#     profil = forms.ImageField(help_text="Upload profile image ")

#     class Meta:
#         model = Costumer
#         fields = ('nameD', 'nameB',  'profil', 'user')

#     def signup(self, request, user):
#         # Save your user
#         user.user = request.user
#         user.nameD = self.cleaned_data['nameD']
#         user.nameB = self.cleaned_data['nameB']
#         user.save()
#         user.userprofile.profil = self.cleaned_data.get('profil')
#         user.userprofile.save()

chat/views.py
from django.shortcuts import render
import json
# Create your views here.


def index(request):
    return render(request,'index.html')


def room(request,room_name):
    context ={
        'room_name':room_name,
        # 'username':request.user.username,
        'username':request.user.usercostumer.username,
    }
    return render(request,'room.html',context)

user/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,logout,authenticate
from .forms import UserForm,FormUser
from .models import Usercostumer
# Create your views here.


def logoutUser(request):
    logout(request)
    return redirect("user:login")

def userlogin(request):
    form = UserForm()
    context = {
        "form": form
    }

    if request.method == "POST":
        if request.POST.get('submit') == 'sign_in':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('chat:index')
            else:
                return render(request, 'user/login.html', {'errorLogin': True})

        elif request.POST.get('submit') == 'sign_up':
            form = FormUser(request.POST)
            if form.is_valid():
                user = form.save()
                return render(request, 'user/login.html')

            else:
                return render(request, 'user/login.html', {'error': True})
        else:
            return render(request, 'user/login.html', {'error': True})

    return render(request, 'user/login.html', context)



def settingProfil(request):
    users = request.user.usercostumer
    form = FormUser(instance=users)
    profil = Usercostumer.objects.get(user=request.user)
    
    if request.method == "POST":
        form = FormUser(request.POST, request.FILES, instance=users)
        if form.is_valid():
            form.save()
            context = {
                "profil": profil,
                'form': form,
            }
            return redirect("user:setting")

    context = {
        "profil": profil,
        'form': form,
    }
    return render(request, 'user/setting.html', context)

templates/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

templates/room.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <title>Chat</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
		
    <link rel="stylesheet" href="{% static 'css/chat.css' %}">  

{% comment %} <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet"> {% endcomment %}
</head>
<body>
   <div class="container-fluid h-5">
					<div class="card-footer"></div>
      </div>
				<div class="col-md-12 col-xl-12 chat ">
					<div class="card">
						<div class="card-header msg_head">
							<div class="d-flex bd-highlight">
								<div class="img_cont">
									<img src="https://static.turbosquid.com/Preview/001292/481/WV/_D.jpg" class="rounded-circle user_img">
								</div>
								<div class="user_info">
									<span class="user_info_name">{{room_name}}</span>
									<p>{{username}}</p>
								</div>
						</div>
						<ul class="penampung">
            </ul>
							
							
						<div class="card-footer">
							<div class="input-group">
								<textarea name="" class="form-control type_msg" placeholder="Type your message..."></textarea>
								<div class="input-group-append">
									<span class="input-group-text send_btn"><i class="fas fa-location-arrow"></i></span>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
    {{ room_name | json_script:"room-name" }}
    {{ username  |  json_script:"username" }}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.js"></script>
	
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
   {% comment %} <script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.js"></script> {% endcomment %}
   <script src="{% static 'js/reconnectwebsocket.js' %}"></script>
   <script src="{% static 'js/chat.js' %}"></script>
    <script>
		window.addEventListener("load", function(){
			chatSocket.send(JSON.stringify({
				'username':username,
				'message': '',
				'command':'get_lates'
			}));
		});
	</script>
    
</body>
</html>

templates/user/login.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load widget_tweaks %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/setting.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    
    
        
    <div class="card">
        <div class="container">
            <form action="" method="POST" id="sign-in" class="sign-in">
            {% csrf_token %}
                <h1 class="text">Login</h1>
                <div class="input-field">
                    <i class="fa fa-user"></i>
                    <input id="email" type="text" name="username" placeholder="username">
                </div>
                <div class="input-field">
                    <i class="fa fa-lock"></i>
                    <input id="password" type="password" name="password" class="password" placeholder="Password">
                    <button class="unmask" type="button"><i class="button fa fa-eye" aria-hidden="true"></i> </button>
                
                </div>

                    {% if errorLogin %}
                <div class="input-field">
                    <i class="fa fa-ban" aria-hidden="true"></i>
                    <h4 class="text-center" placeholder="wrong trua agian">wrong / Try again</h4>
                </div>
                    {% endif %}
                    
                <button class="btn" type='submit' name='submit' value='sign_in'>Sign In</button>
                
            </form>
            <form action="" method="POST" id="sign-up" class="sign-up">
            {% csrf_token %}
                <h1 class="text">SIGN UP</h1>
                <div class="input-field">
                    <i class="fa fa-user"></i>
                    {% render_field form.username  placeholder="Username...." %}
                </div>
                <div class="input-field">
                    <i class="fa fa-envelope"></i>
                    {% render_field form.email id="email"  placeholder="Email...." %}
                </div>
                <div class="input-field row">
                    <i class="fa fa-lock"></i>
                     {% render_field form.password1 class="password"  placeholder="Password " %}
                     <button class="unmask" type="button"><i class="button fa fa-eye" aria-hidden="true"></i> </button>
                </div>
                <div class="input-field">
                    <i class="fa fa-lock"></i>
                    {% render_field form.password2 class="password"  placeholder="Password Confirm" %}
                    <button class="unmask" type="button" style="border:0;"><i class="button fa fa-eye" aria-hidden="true"></i> </button>
                </div>
                        {% if error  %}
                <div class="input-field">
                            <i class="fa fa-info-circle" aria-hidden="true"></i>
                            <p>Sign Not Valid</p>
                </div>
                        {% endif %}
                <button class="btn" type='submit' name='submit' value='sign_up'>Sign UP</button>
                
            </form>
        </div>
    </div>
    <div class="left-panel">
        <div id="sign-up-btn" class="sign-up-btn" >
            <h1 class="panel">Dont have account?</h1>
            <h3 class="panel">create account to more experience</h3>
            <input class="btn-signup" onclick="signup()" type="button" value="SIGN UP">
        </div>
        <div id="sign-in-btn" class="sign-in-btn" style="display:none;">
            <h1 class="panel">Have account</h1>
            <h3 class="panel">login if you have some</h3>
            <input class="btn-signup" onclick="signin()" type="button" value="SIGN IN">
        </div>
    </div>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    <script src="{% static 'js/setting.js' %}"></script>
    <script>
        $('.unmask').on('click', function () {
        if ($(this).prev('input').attr('type') == 'password')
            $(this).prev('input').prop('type', 'text');
        else
            $(this).prev('input').prop('type', 'password');
        return false;
        });
    </script>
    
        {% if error %}
    <script>
        function signup() {
                $('#sign-up').removeClass("sign-up").addClass("sign-up-2");
                $('#sign-in').removeClass("sign-in").addClass("sign-in-2");
                    let btn = document.getElementById('sign-up-btn');
                    let btn_2 = document.getElementById('sign-in-btn')
                        btn.style.display = "none";
                        btn_2.style.display = "";
        }
        signup()
    </script>
        {% endif %}

</body>

</html>

{% comment %} /accounts/github/login/?process=login&amp;next=%2F {% endcomment %}

templates/user/setting.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<html lang="en">
<head>
<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Set {{profil.username}}</title>
    <link rel="stylesheet" href="{% static 'css/settingForm.css' %}">
</head>
<body>

    {% comment %} <link rel="stylesheet" href="{% static 'css/card.css' %}"> {% endcomment %}
<div class="container">
	<div class="row">

            <div class="card hovercard">
                {% comment %} <div class="cardheader" style="background:url('http://127.0.0.1:8000{{profil.background.url}}') ;height: 350px;background-repeat: no-repeat;background-size: cover; background-position: center;"> {% endcomment %}

                </div>
                <div class="avatar">
                    <img alt="KOSONG" src="{{profil.profil.url}}">
                </div>
                <div class="info">
                    <div class="title">
                        <a target="_blank" href="">{{profil.username}}</a>
                    </div>
                </div>
                {% comment %} <div class="bottom">
                    <a class="btn btn-primary btn-twitter btn-sm" href="https://twitter.com/webmaniac">
                        <i class="fa fa-twitter"></i>
                    </a>
                    <a class="btn btn-danger btn-sm" rel="publisher"
                       href="https://plus.google.com/+ahmshahnuralam">
                        <i class="fa fa-google-plus"></i>
                    </a>
                    <a class="btn btn-primary btn-sm" rel="publisher"
                       href="https://plus.google.com/shahnuralam">
                        <i class="fa fa-facebook"></i>
                    </a>
                    <a class="btn btn-warning btn-sm" rel="publisher" href="https://plus.google.com/shahnuralam">
                        <i class="fa fa-behance"></i>
                    </a>
                </div> {% endcomment %}
            </div>

      

	</div>

        <div class="text-center">
        <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
        {% render_field form.username class="form-control"  placeholder="username ....." %}
        </div>
        <div class="form-group">
        {% render_field form.bio class="form-control"  placeholder="bio ....." %}
        </div>
        <div class="form-group">
        <label for=""></label>
        {% render_field form.status class="form-control"  placeholder=" status" %}
        </div>

        <div class="file-upload">
            <button class="file-upload-btn" type="button" onclick="$('.file-upload-input').trigger('click')">Add Image</button>
            <div class="image-upload-wrap">
            {% render_field form.profil id="id_profil" name="profil" class="file-upload-input"  onchange="readURL(this);" %}
                {% comment %} <input class="file-upload-input" type='file' onchange="readURL(this);" accept="image/*" /> {% endcomment %}
                <div class="drag-text">
                <h3>Drag and drop a file or select add Image</h3>
                </div>
            </div>
            <div class="file-upload-content">
                <img class="file-upload-image" src="{{profil.profil.url}}" alt="your image" />
                <div class="image-title-wrap">
                <button type="button" onclick="removeUpload()" class="remove-image">Remove <span class="image-title">Uploaded Image</span></button>
                </div>
            </div>
        </div>
        <button class="btn btn-primary form-control" type="submit">submit</button>
        </form>
        </div>
    </div>
    
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="{% static 'js/settingFrom.js' %}"> </script>
</body>
</html>